services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.prod
        restart: always
        environment:
            PORT: 8080
        volumes:
            - /etc/dokploy/mounts/cmc-uploads:/app/public/uploads
        networks:
            - dokploy-network

networks:
    dokploy-network:
        external: true
