import { configApp } from '@adonisjs/eslint-config';

export default [
    ...configApp({
        rules: {
            semi: ['error', 'always'],
            '@stylistic/comma-dangle': ['error', 'always-multiline'],
        },
    }),
    // Auto-generated by Lucid (`node ace migration:run`) — never edited by hand, so linting it is pointless.
    { ignores: ['database/schema.ts'] },
];
