/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  Auth: () => import('#controllers/auth_controller'),
  EmailVerification: () => import('#controllers/email_verification_controller'),
  ForgotPassword: () => import('#controllers/forgot_password_controller'),
  Legal: () => import('#controllers/legal_controller'),
  PasswordReset: () => import('#controllers/password_reset_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Register: () => import('#controllers/register_controller'),
  Simulator: () => import('#controllers/simulator_controller'),
  Terms: () => import('#controllers/terms_controller'),
}
