/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Buybacks: () => import('#controllers/admin/buybacks_controller'),
    Castellanies: () => import('#controllers/admin/castellanies_controller'),
    Commandes: () => import('#controllers/admin/commandes_controller'),
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Devis: () => import('#controllers/admin/devis_controller'),
    Licenses: () => import('#controllers/admin/licenses_controller'),
    Livraisons: () => import('#controllers/admin/livraisons_controller'),
    Materials: () => import('#controllers/admin/materials_controller'),
    OrderArchives: () => import('#controllers/admin/order_archives_controller'),
    Organizations: () => import('#controllers/admin/organizations_controller'),
    Resources: () => import('#controllers/admin/resources_controller'),
    Tonneau: () => import('#controllers/admin/tonneau_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  Auth: () => import('#controllers/auth_controller'),
  Buybacks: () => import('#controllers/buybacks_controller'),
  Commandes: () => import('#controllers/commandes_controller'),
  Deposits: () => import('#controllers/deposits_controller'),
  Devis: () => import('#controllers/devis_controller'),
  Home: () => import('#controllers/home_controller'),
  Livraisons: () => import('#controllers/livraisons_controller'),
  Organigramme: () => import('#controllers/organigramme_controller'),
  Organization: () => import('#controllers/organization_controller'),
  Pickaxes: () => import('#controllers/pickaxes_controller'),
  Stocks: () => import('#controllers/stocks_controller'),
  Tarifs: () => import('#controllers/tarifs_controller'),
}
