/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm';
import { DateTime } from 'luxon';

export class TermsVersionSchema extends BaseModel {
    static $columns = ['createdAt', 'gracePeriodDays', 'id', 'invalidatedAt', 'note', 'updatedAt'] as const;
    $columns = TermsVersionSchema.$columns;
    @column.dateTime({ autoCreate: true })
    declare createdAt: DateTime;
    @column()
    declare gracePeriodDays: number;
    @column({ isPrimary: true })
    declare id: string;
    @column.dateTime()
    declare invalidatedAt: DateTime;
    @column()
    declare note: string | null;
    @column.dateTime({ autoCreate: true, autoUpdate: true })
    declare updatedAt: DateTime | null;
}

export class UserTokenSchema extends BaseModel {
    static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'type', 'userId'] as const;
    $columns = UserTokenSchema.$columns;
    @column.dateTime({ autoCreate: true })
    declare createdAt: DateTime;
    @column.dateTime()
    declare expiresAt: DateTime;
    @column({ isPrimary: true })
    declare id: string;
    @column()
    declare tokenHash: string;
    @column()
    declare type: string;
    @column()
    declare userId: string;
}

export class UserSchema extends BaseModel {
    static $columns = ['acceptedTermsAt', 'createdAt', 'deletionWarningSentAt', 'email', 'enabled', 'id', 'lastLoginAt', 'password', 'role', 'updatedAt', 'username'] as const;
    $columns = UserSchema.$columns;
    @column.dateTime()
    declare acceptedTermsAt: DateTime | null;
    @column.dateTime({ autoCreate: true })
    declare createdAt: DateTime;
    @column.dateTime()
    declare deletionWarningSentAt: DateTime | null;
    @column()
    declare email: string;
    @column()
    declare enabled: boolean | null;
    @column({ isPrimary: true })
    declare id: string;
    @column.dateTime()
    declare lastLoginAt: DateTime | null;
    @column({ serializeAs: null })
    declare password: string | null;
    @column()
    declare role: string;
    @column.dateTime({ autoCreate: true, autoUpdate: true })
    declare updatedAt: DateTime | null;
    @column()
    declare username: string;
}
