/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type MaterialTransformer from '#transformers/material_transformer'
import type OrganizationTransformer from '#transformers/organization_transformer'
import type ResourceTransformer from '#transformers/resource_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type CastellanyTransformer from '#transformers/castellany_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Material = InferData<MaterialTransformer>
  export namespace Material {
    export type Variants = InferVariants<MaterialTransformer>
  }
  export type Organization = InferData<OrganizationTransformer>
  export namespace Organization {
    export type Variants = InferVariants<OrganizationTransformer>
  }
  export type Resource = InferData<ResourceTransformer>
  export namespace Resource {
    export type Variants = InferVariants<ResourceTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type Castellany = InferData<CastellanyTransformer>
  export namespace Castellany {
    export type Variants = InferVariants<CastellanyTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
