const placeholder = {};
const routes = {
    'home': {
        methods: ["GET", "HEAD"],
        pattern: '/',
        tokens: [{ "old": "/", "type": 0, "val": "/", "end": "" }],
        types: placeholder,
    },
    'simulator.index': {
        methods: ["GET", "HEAD"],
        pattern: '/simulation',
        tokens: [{ "old": "/simulation", "type": 0, "val": "simulation", "end": "" }],
        types: placeholder,
    },
    'simulator.store': {
        methods: ["POST"],
        pattern: '/simulation',
        tokens: [{ "old": "/simulation", "type": 0, "val": "simulation", "end": "" }],
        types: placeholder,
    },
    'simulator.show': {
        methods: ["GET", "HEAD"],
        pattern: '/simulation/:id',
        tokens: [{ "old": "/simulation/:id", "type": 0, "val": "simulation", "end": "" }, { "old": "/simulation/:id", "type": 1, "val": "id", "end": "" }],
        types: placeholder,
    },
    'simulator.announce': {
        methods: ["POST"],
        pattern: '/simulation/:id/announce',
        tokens: [{ "old": "/simulation/:id/announce", "type": 0, "val": "simulation", "end": "" }, { "old": "/simulation/:id/announce", "type": 1, "val": "id", "end": "" }, { "old": "/simulation/:id/announce", "type": 0, "val": "announce", "end": "" }],
        types: placeholder,
    },
    'simulator.uploadAnnouncement': {
        methods: ["POST"],
        pattern: '/simulation/:id/upload',
        tokens: [{ "old": "/simulation/:id/upload", "type": 0, "val": "simulation", "end": "" }, { "old": "/simulation/:id/upload", "type": 1, "val": "id", "end": "" }, { "old": "/simulation/:id/upload", "type": 0, "val": "upload", "end": "" }],
        types: placeholder,
    },
    'simulator.updateAnnouncement': {
        methods: ["PATCH"],
        pattern: '/simulation/:id/announcements/:announcementId',
        tokens: [{ "old": "/simulation/:id/announcements/:announcementId", "type": 0, "val": "simulation", "end": "" }, { "old": "/simulation/:id/announcements/:announcementId", "type": 1, "val": "id", "end": "" }, { "old": "/simulation/:id/announcements/:announcementId", "type": 0, "val": "announcements", "end": "" }, { "old": "/simulation/:id/announcements/:announcementId", "type": 1, "val": "announcementId", "end": "" }],
        types: placeholder,
    },
    'simulator.destroyAnnouncement': {
        methods: ["DELETE"],
        pattern: '/simulation/:id/announcements/:announcementId',
        tokens: [{ "old": "/simulation/:id/announcements/:announcementId", "type": 0, "val": "simulation", "end": "" }, { "old": "/simulation/:id/announcements/:announcementId", "type": 1, "val": "id", "end": "" }, { "old": "/simulation/:id/announcements/:announcementId", "type": 0, "val": "announcements", "end": "" }, { "old": "/simulation/:id/announcements/:announcementId", "type": 1, "val": "announcementId", "end": "" }],
        types: placeholder,
    },
    'simulator.nextMonth': {
        methods: ["POST"],
        pattern: '/simulation/:id/next-month',
        tokens: [{ "old": "/simulation/:id/next-month", "type": 0, "val": "simulation", "end": "" }, { "old": "/simulation/:id/next-month", "type": 1, "val": "id", "end": "" }, { "old": "/simulation/:id/next-month", "type": 0, "val": "next-month", "end": "" }],
        types: placeholder,
    },
    'simulator.respondEvent': {
        methods: ["POST"],
        pattern: '/simulation/:id/respond-event',
        tokens: [{ "old": "/simulation/:id/respond-event", "type": 0, "val": "simulation", "end": "" }, { "old": "/simulation/:id/respond-event", "type": 1, "val": "id", "end": "" }, { "old": "/simulation/:id/respond-event", "type": 0, "val": "respond-event", "end": "" }],
        types: placeholder,
    },
    'simulator.advisor': {
        methods: ["POST"],
        pattern: '/simulation/:id/advisor',
        tokens: [{ "old": "/simulation/:id/advisor", "type": 0, "val": "simulation", "end": "" }, { "old": "/simulation/:id/advisor", "type": 1, "val": "id", "end": "" }, { "old": "/simulation/:id/advisor", "type": 0, "val": "advisor", "end": "" }],
        types: placeholder,
    },
    'simulator.destroy': {
        methods: ["DELETE"],
        pattern: '/simulation/:id',
        tokens: [{ "old": "/simulation/:id", "type": 0, "val": "simulation", "end": "" }, { "old": "/simulation/:id", "type": 1, "val": "id", "end": "" }],
        types: placeholder,
    },
    'password.reset.show': {
        methods: ["GET", "HEAD"],
        pattern: '/password-reset',
        tokens: [{ "old": "/password-reset", "type": 0, "val": "password-reset", "end": "" }],
        types: placeholder,
    },
    'password.reset.update': {
        methods: ["POST"],
        pattern: '/password-reset',
        tokens: [{ "old": "/password-reset", "type": 0, "val": "password-reset", "end": "" }],
        types: placeholder,
    },
    'profile.show': {
        methods: ["GET", "HEAD"],
        pattern: '/profile',
        tokens: [{ "old": "/profile", "type": 0, "val": "profile", "end": "" }],
        types: placeholder,
    },
    'profile.export': {
        methods: ["GET", "HEAD"],
        pattern: '/profile/export',
        tokens: [{ "old": "/profile/export", "type": 0, "val": "profile", "end": "" }, { "old": "/profile/export", "type": 0, "val": "export", "end": "" }],
        types: placeholder,
    },
    'profile.update': {
        methods: ["PUT"],
        pattern: '/profile',
        tokens: [{ "old": "/profile", "type": 0, "val": "profile", "end": "" }],
        types: placeholder,
    },
    'profile.passwordReset': {
        methods: ["POST"],
        pattern: '/profile/password-reset',
        tokens: [{ "old": "/profile/password-reset", "type": 0, "val": "profile", "end": "" }, { "old": "/profile/password-reset", "type": 0, "val": "password-reset", "end": "" }],
        types: placeholder,
    },
    'profile.destroy': {
        methods: ["DELETE"],
        pattern: '/profile',
        tokens: [{ "old": "/profile", "type": 0, "val": "profile", "end": "" }],
        types: placeholder,
    },
    'login': {
        methods: ["GET", "HEAD"],
        pattern: '/login',
        tokens: [{ "old": "/login", "type": 0, "val": "login", "end": "" }],
        types: placeholder,
    },
    'auth.login.store': {
        methods: ["POST"],
        pattern: '/login',
        tokens: [{ "old": "/login", "type": 0, "val": "login", "end": "" }],
        types: placeholder,
    },
    'forgot.password': {
        methods: ["GET", "HEAD"],
        pattern: '/forgot-password',
        tokens: [{ "old": "/forgot-password", "type": 0, "val": "forgot-password", "end": "" }],
        types: placeholder,
    },
    'forgot.password.store': {
        methods: ["POST"],
        pattern: '/forgot-password',
        tokens: [{ "old": "/forgot-password", "type": 0, "val": "forgot-password", "end": "" }],
        types: placeholder,
    },
    'register': {
        methods: ["GET", "HEAD"],
        pattern: '/register',
        tokens: [{ "old": "/register", "type": 0, "val": "register", "end": "" }],
        types: placeholder,
    },
    'register.store': {
        methods: ["POST"],
        pattern: '/register',
        tokens: [{ "old": "/register", "type": 0, "val": "register", "end": "" }],
        types: placeholder,
    },
    'email.verify': {
        methods: ["GET", "HEAD"],
        pattern: '/email-verify',
        tokens: [{ "old": "/email-verify", "type": 0, "val": "email-verify", "end": "" }],
        types: placeholder,
    },
    'auth.logout': {
        methods: ["DELETE"],
        pattern: '/logout',
        tokens: [{ "old": "/logout", "type": 0, "val": "logout", "end": "" }],
        types: placeholder,
    },
    'admin.dashboard': {
        methods: ["GET", "HEAD"],
        pattern: '/admin',
        tokens: [{ "old": "/admin", "type": 0, "val": "admin", "end": "" }],
        types: placeholder,
    },
    'admin.terms.invalidate': {
        methods: ["POST"],
        pattern: '/admin/terms/invalidate',
        tokens: [{ "old": "/admin/terms/invalidate", "type": 0, "val": "admin", "end": "" }, { "old": "/admin/terms/invalidate", "type": 0, "val": "terms", "end": "" }, { "old": "/admin/terms/invalidate", "type": 0, "val": "invalidate", "end": "" }],
        types: placeholder,
    },
    'admin.users.index': {
        methods: ["GET", "HEAD"],
        pattern: '/admin/users',
        tokens: [{ "old": "/admin/users", "type": 0, "val": "admin", "end": "" }, { "old": "/admin/users", "type": 0, "val": "users", "end": "" }],
        types: placeholder,
    },
    'admin.users.show': {
        methods: ["GET", "HEAD"],
        pattern: '/admin/users/:id',
        tokens: [{ "old": "/admin/users/:id", "type": 0, "val": "admin", "end": "" }, { "old": "/admin/users/:id", "type": 0, "val": "users", "end": "" }, { "old": "/admin/users/:id", "type": 1, "val": "id", "end": "" }],
        types: placeholder,
    },
    'admin.users.export': {
        methods: ["GET", "HEAD"],
        pattern: '/admin/users/:id/export',
        tokens: [{ "old": "/admin/users/:id/export", "type": 0, "val": "admin", "end": "" }, { "old": "/admin/users/:id/export", "type": 0, "val": "users", "end": "" }, { "old": "/admin/users/:id/export", "type": 1, "val": "id", "end": "" }, { "old": "/admin/users/:id/export", "type": 0, "val": "export", "end": "" }],
        types: placeholder,
    },
    'admin.users.update': {
        methods: ["PUT"],
        pattern: '/admin/users/:id',
        tokens: [{ "old": "/admin/users/:id", "type": 0, "val": "admin", "end": "" }, { "old": "/admin/users/:id", "type": 0, "val": "users", "end": "" }, { "old": "/admin/users/:id", "type": 1, "val": "id", "end": "" }],
        types: placeholder,
    },
    'legal.show': {
        methods: ["GET", "HEAD"],
        pattern: '/legal',
        tokens: [{ "old": "/legal", "type": 0, "val": "legal", "end": "" }],
        types: placeholder,
    },
    'terms.show': {
        methods: ["GET", "HEAD"],
        pattern: '/terms',
        tokens: [{ "old": "/terms", "type": 0, "val": "terms", "end": "" }],
        types: placeholder,
    },
    'terms.accept': {
        methods: ["POST"],
        pattern: '/terms/accept',
        tokens: [{ "old": "/terms/accept", "type": 0, "val": "terms", "end": "" }, { "old": "/terms/accept", "type": 0, "val": "accept", "end": "" }],
        types: placeholder,
    },
};
export { routes };
export const registry = {
    routes,
    $tree: {},
};
